name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  GKE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-southeast1
  GKE_CLUSTER: devops-test
  GKE_ZONE: asia-southeast1
  DEPLOYMENT_NAME: echo-hello-world
  REPOSITORY: echo-hello-world
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/echo-hello-world:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: 'GoogleCloudPlatform/github-actions/setup-gcloud@v0.2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
        
      - name: Build and Push Docker Image
        run: |
          docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$GKE_PROJECT/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/echo-hello-world:${{ github.sha }}

      - name: Set up Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |
          ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=$GAR_LOCATION-docker.pkg.dev/$GKE_PROJECT/$REPOSITORY/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
